library(ggplot2)
library(reshape2)
args<-commandArgs(TRUE)
denstats<-read.table(args[1], sep=",", header=TRUE)
denmelt<-melt(denstats, id="position")
pdfname<-paste(strsplit(args[1], "[.]")[[1]][1], ".pdf", sep = "")
pdf(pdfname,width=20,height=12,paper='special')
ggplot(denmelt, aes(x=position, y=value, colour=variable)) + geom_point() + stat_smooth() + facet_wrap(~variable, scales = "free_y", drop = FALSE)
dev.off()
